[package]
name = "scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
# members
common.workspace = true
messages.workspace = true

# misc
crossbeam.workspace = true
derive_more.workspace = true
tokio.workspace = true
tracing.workspace = true
