[package]
name = "messages"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
# members
common.workspace = true
proof-proto.workspace = true

# misc
derive_more.workspace = true
