[package]
name = "eth-proofs"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[[bin]]
name = "eth-proofs"
path = "src/main.rs"

[dependencies]
# members
common.workspace = true
fetch-service.workspace = true
fetcher.workspace = true
messages.workspace = true
proof-service.workspace = true
proving-client.workspace = true
proving-mock.workspace = true
reporter.workspace = true
scheduler.workspace = true

# misc
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
futures.workspace = true
reqwest.workspace = true
tokio.workspace = true
