[package]
name = "reporter"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
# members
common.workspace = true
messages.workspace = true

# misc
derive_more.workspace = true
tokio.workspace = true
tracing.workspace = true
