[package]
name = "test-clients"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[[bin]]
name = "prove-block-by-number"
path = "src/prove_block_by_number.rs"

[[bin]]
name = "prove-latest-block"
path = "src/prove_latest_block.rs"

[[bin]]
name = "reproduce-block-by-number"
path = "src/reproduce_block_by_number.rs"

[dependencies]
# members
common.workspace = true
fetch-client.workspace = true

# misc
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
reqwest.workspace = true
tokio.workspace = true
